name:  First Workflow
on:  workflow_dispatch
jobs:
  first-job:
    runs-on:  windows-latest
    steps:
      - name:  Welcome
        run:  echo "My first Job
      - name:  Second Step
        run:  echo "Second Job"
  second-job:
     # needs:  first-job
     runs-on:  windows-latest
     steps:
      - name:  Job2Step1
        run:  echo "My Second Job"
      - name:  Job2Step2
        run:  echo "Steps"
     
        
